---
title: "shareholder breakdown graph ONT"
author: "Holly Ormond"
date: "2022-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Financial info from ONT 2022 HY finincial statements.
```{r}
### make df 
sh <- c("Individual Insiders 2.1%", "Public Companies 5.3%", "Private Companies 11.4%", "General Public 11.6%", "Venture Capital and Private Equity Firms 20.5%", "Institutional Investors 49.2%") 

shares <- c(17337838,43354397, 93493000, 95773509, 168420844, 404745034)
df <- data.frame(sh, shares)

library(dplyr)
df %>% mutate(Percentage = round(shares/sum(shares) * 100, 1))

# Individual_Insiders <- 17337838
# Public_Companies <- 43354397
# Private_Companies <- 93493000
# General_Public <- 95773509
# VC_PE_Firms <- 168420844
# Institutional_Investors <- 404745034
```


```{r}
# df
library(wesanderson)
#names(wes_palettes)

library("viridis")  

library(RColorBrewer)
display.brewer.all()
```
```{r}
### making my own 
cp <- c("#fca827", "#085c74", "#ac047c")

#### colour blind palette 
cbp <- c("#D99F1D", "#9A9DBF", "#752428", "#3B4C92", "#6A865A", "#4A4D65")
```


```{r}
# make treemap 

library(treemap)
tiff('own_struc.tiff', units="in", width=10, height=5, res=600, compression = 'lzw')

# Plot
shareholder_tm <- treemap(df,
            
            # data
            index="sh",
            vSize="shares",
            type="index",
            
            # # Main
            title="Ownership Structure",
            palette= cbp,
            algorithm="pivotSize",
            mirror.y=F,
            # 
            # Borders:
            border.col=c("black"),             
            border.lwds=1,                         
            # 
            # # Labels
            fontcolor.labels="black",
            fontface.labels=1.0)

dev.off()
```
##### Cost of sequencing technology
## see: https://docs.google.com/presentation/d/e/2PACX-1vTzEQ65KsEQPVoU85ezzzYtLRM7lmukkTuJbmsJLmGKmcIbg3VzdbJjMKqr3J-2ECkCEs65NxXq_VJ1/pub?start=false&loop=false&delayms=3000&slide=id.g161450d19cf_0_0
## and: https://docs.google.com/spreadsheets/d/1GMMfhyLK0-q8XkIo3YxlWaZA5vVMuhU1kg41g4xLkXc/edit?hl=en_GB&hl=en_GB#gid=1569422585
```{r}
##load xlsx data 
library(readxl)
ngs <- read_excel("/Users/hollyormond/Documents/Uni/Third Year/SCIE310/SCIE310_Project_Assignment_2/price_ngs.xlsx")
ngs #view df
```


```{r}
##make new row from price max and min
ngs$average_price_per_Gb_USD <- rowMeans(ngs[ , c(2,3)], na.rm=TRUE)
```

```{r}
##legend = company
ngs$company <- c("Oxford Nanopore", "Oxford Nanopore", "Oxford Nanopore", "Oxford Nanopore", "Oxford Nanopore", "Oxford Nanopore", "Oxford Nanopore", "Oxford Nanopore", "Illumina", "Illumina", "Illumina", "Illumina", "Illumina", "Illumina", "Illumina", "Illumina", "Illumina", "Illumina", "Illumina", "PacBio")
ngs
```
```{r}
## remove row with NA
#ngs <- ngs[-17,]
ngs
```
```{r}
ngs$platform <- c("Flongle 1fcell 126 channels", "MinION Mk1b 1fcell 512 channels", "MinION Mk1c 1fcell 512 channels", "GridION X5 5fcell", "P2 Solo 1fcell", "P2 1fcell", "PromethION 24fcell 10,700 channels", "PromethION 48fcell 10,700 channels", "NovaSeq SP 2fcell", "NovaSeq S1 2fcell", "NovaSeq S2 2fcell", "NovaSeq S4 v1.5 2fcell", "iSeq 100 1fcell", "MiniSeq 1fcell", "ILMN MiSeq 1fcell", "NextSeq 550 1fcell", "NextSeq 1000 P1/P2 1fcell", "NextSeq 2000 P3 1fcell", "8M Sequel II/IIe v2.0 chem 1fcell")
```

```{r}
ngs
```
```{r}
# Init Ggplot
gg_ngs<-ggplot(data = ngs, aes(x = machine_price_USD, y = average_price_per_Gb_USD, color = company, size = reagent_max_price_USD)) +
  geom_text_repel(aes(label = platform, size = 100, segment.alpha = 0.2), 
                  show.legend = F, #removes an 'a' in legend points
                  force = 40, 
                  force_pull = 2, 
                  segment.angle = 1,
                  segment.ncp = 10) + 
  geom_point(alpha = 0.6) + #alpha is transparency
  labs(title = "Average Cost Per Gigabase (Gb) vs Initial Cost of Sequencing Platform",
         x = "Initial Cost of Sequencing Platform USD",
         y = "Average Cost Per Gb USD") +
    guides(colour = guide_legend(title = "Company", order = 1), size = guide_legend(title = "Max cost of reagents", order = 2))
gg_ngs
```


```{r}
# size scaled appropriately so as not to be misleading, no cost reagent size
gg_ngs2<-ggplot(data = ngs, 
                aes(x = machine_price_USD, y = average_price_per_Gb_USD, color = company)) +
  geom_text_repel(aes(label = platform, size = 550, segment.alpha = 0.2),
                  size = 1.8,
                  show.legend = F, #removes an 'a' in legend points
                  force = 40, 
                  force_pull = 2, 
                  segment.angle = 1,
                  segment.ncp = 10) + 
  geom_point(alpha = 0.6) + #transparency
  labs(title = "Average Cost Per Gb vs Initial Cost of Sequencing Platform",
         x = "Initial Cost of Sequencing Platform (USD)",
         y = "Average Cost Per Gb (USD)") +
  guides(colour = guide_legend(title = "Company")) +
  scale_y_continuous(limits=c(0, 650), breaks=seq(0,650,100))
gg_ngs2
```
```{r}
#### with company colours colous. 
# size scaled appropriately so as not to be misleading, no cost reagent size
library(ggrepel)

gg_ngs2<-ggplot(data = ngs, 
                aes(x = machine_price_USD, y = average_price_per_Gb_USD, color = company)) +
  geom_text_repel(aes(label = platform, size = 550, segment.alpha = 0.2),
                  size = 1.8,
                  show.legend = F, #removes an 'a' in legend points
                  force = 50, 
                  force_pull = 0, 
                  segment.angle = 1,
                  segment.ncp = 10) + #point colour +
  geom_point(alpha = 0.6) + #transparency
  scale_color_manual(values=cp) +
  labs(title = "Average Cost Per Gb vs Initial Cost of Sequencing Platform",
         x = "Initial Cost of Sequencing Platform (USD)",
         y = "Average Cost Per Gb (USD)") +
  guides(color = guide_legend(title = "Company")) +
  scale_y_continuous(limits=c(0, 650), breaks=seq(0,650,100))

gg_ngs2

#ggsave("cost_v_Gb.tiff", units="in", width=10, height=4, dpi=300, compression = 'lzw')

```

```{r}
## rem bg
library(ggrepel)

gg_ngs2<-ggplot(data = ngs, 
                aes(x = machine_price_USD, y = average_price_per_Gb_USD, color = company)) +
  geom_text_repel(aes(label = platform, size = 550, segment.alpha = 0.2),
                  size = 1.8,
                  show.legend = F, #removes an 'a' in legend points
                  force = 50, 
                  force_pull = 0, 
                  segment.angle = 1,
                  segment.ncp = 10) + #point colour +
  geom_point(alpha = 0.6) + #transparency
  scale_color_manual(values=cp) +
  labs(title = "                              Average Cost Per Gb vs Initial Cost of Sequencing Platform",
         x = "Initial Cost of Sequencing Platform (USD)",
         y = "Average Cost Per Gb (USD)") +
  guides(color = guide_legend(title = "Company")) +
  scale_y_continuous(limits=c(0, 650), breaks=seq(0,650,100)) +
    theme( # remove the horizontal grid lines
         panel.grid.major.y = element_line( size=.1, color="grey"),
         panel.grid.minor.x = element_line(),
         panel.grid.major.x = element_line( size=.1, color="grey"), # explicitly set the horizontal lines (or they will disappear too)
         panel.background = element_blank(),
#         panel.border = element_rect(color = "grey")
    )

gg_ngs2

ggsave("cost_v_Gb2.tiff", units="in", width=10, height=4, dpi=300, compression = 'lzw')


```

## test
```{r}
set.seed(1)
library(ggplot2)
library(ggrepel)
df <- data.frame(n=runif(8),y=1:8,l=letters[1:8],col=palette.colors(8))

p_vol <- ggplot(df, aes(n, y, label = l)) +
  geom_point(aes(fill=l),color = df$col) +
  geom_text_repel(col=df$col)+theme_classic()
print(p_vol)

##
p_vol2 <- ggplot(df, aes(n, y, label = l)) +
  geom_point(aes(fill=l, color = l)) +
  geom_text_repel(col=df$col) +
  theme_classic() +
  scale_fill_manual(values=c("#CC0000", "#006600", "#669999", "#00CCCC", 
                             "#660099", "#CC0066", "#FF9999", "#FF9900"))
print(p_vol2)


```

```{r}
##1000/average_price_per_Gb_USD

ngs$number_of_Gb_for_1k_USD <- c(17.78, 26.14, 26.14, 26.14, 50.63, 142.86, 160.00, 160.00, 52.42, 57.42, 76.90, 55.60, 2.06, 2.60, 1.61, 18.53, 21.86, 35.57, 39.60)
ngs
```


```{r}
## plot average number of gb per 1k
p<-ggplot(data=ngs, aes(x=reorder(platform, number_of_Gb_for_1k_USD), y=number_of_Gb_for_1k_USD, fill=company)) +
  geom_bar(stat="identity", width=0.5) +
  coord_flip() +
  labs(title = "                            Gigabases (Gb) Per $1,000 USD",
         x =  "Sequencing Platform",
         y = "Average Number of Gb per $1,000 USD") +
  guides(fill = guide_legend(title = "Company")) +
  scale_fill_manual(values = cp, name = "") +
  theme( # remove the horizontal grid lines
         panel.grid.major.y = element_blank(),
         panel.grid.minor.x = element_line(),
         panel.grid.major.x = element_line( size=.1, color="grey"), # explicitly set the horizontal lines (or they will disappear too)
         panel.background = element_blank(),
#         panel.border = element_rect(color = "grey")
    )
#  scale_x_binned(c(0,150))
  
p
ggsave("gb1k.tiff", units="in", width=10, height=4, dpi=300, compression = 'lzw')

```


```{r}
## get values
Minimum <-c(525, 315, 648, 885)
Maximum <- c(1075, 1400, 3897, 4770)
platform <- c("Illumina NovaSeq S4", "ONT PromethION", "PACB 8M Sequel II v2.0 chem 1 flowcell", "ONT MinION Mk 1B 1fcell")
```


```{r}
library(ggplot2)
library(reshape2)
library(wesanderson)

df1 <- data.frame(Minimum, Maximum, platform)
df_hg <- melt(df1, id.vars='platform')

ggplot(df_hg, aes(x=platform, y=value, fill=variable)) +
  geom_bar(stat='identity', position='dodge') +
  scale_fill_manual(values = cp, name = "") +
  coord_flip() +
    labs(title = "Cost of Sequencing a Human Genome (USD)",
         x =  "Sequencing Platform",
         y = "Cost (USD)") +
  guides(fill = guide_legend(title = ""))

ggsave("cost_seq_hg.tiff", units="in", width=10, height=4, dpi=300, compression = 'lzw')

```


```{r}
library(reshape2)

df1 <- data.frame(Minimum, Maximum, platform)
df_hg <- melt(df1, id.vars='platform')
```


```{r}
g2 <- ggplot(df_hg, aes(x=platform, y=value, fill=variable)) +
  geom_bar(stat='identity', position='dodge') +
  coord_flip() +
  labs(title = "                           Cost of Sequencing a Human Genome (USD)",
         x =  "Sequencing Platform",
         y = "Cost (USD)") +
  guides(fill = guide_legend(title = "")) +
  scale_fill_manual(values = cp, name = "") +
  theme( # remove the horizontal grid lines
         panel.grid.major.y = element_blank(),
         panel.grid.minor.x = element_line(),
         panel.grid.major.x = element_line( size=.1, color="grey"), # explicitly set the horizontal lines (or they will disappear too)
         panel.background = element_blank(),
#         panel.border = element_rect(color = "grey")
    )
g2
ggsave("hg_cost.tiff", units="in", width=10, height=4, dpi=300, compression = 'lzw')

```


